<a href="https://colab.research.google.com/github/Dounia-Nassar/Fraud-Detection-Credit-Card-Transactions/blob/main/Anomaly_Detection(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [ ]:
#Mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Load data
path="/content/drive/MyDrive/AXSOSACADEMY/03-IntermediateML/Week18/Data/credit_card.csv"
df=pd.read_csv(path)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      10000 non-null  float64
 1   V2      10000 non-null  float64
 2   V3      10000 non-null  float64
 3   V4      10000 non-null  float64
 4   V5      10000 non-null  float64
 5   V6      10000 non-null  float64
 6   V7      10000 non-null  float64
 7   V8      10000 non-null  float64
 8   V9      10000 non-null  float64
 9   V10     10000 non-null  float64
 10  V11     10000 non-null  float64
 11  V12     10000 non-null  float64
 12  V13     10000 non-null  float64
 13  V14     10000 non-null  float64
 14  V15     10000 non-null  float64
 15  V16     10000 non-null  float64
 16  V17     10000 non-null  float64
 17  V18     10000 non-null  float64
 18  V19     10000 non-null  float64
 19  V20     10000 non-null  float64
 20  V21     10000 non-null  float64
 21  V22     10000 non-null  float64
 22  V23     10000 non-null  float64
 23  V24     10000 non-null  float64
 24  V25     10000 non-null  float64
 25  V26     10000 non-null  float64
 26  V27     10000 non-null  float64
 27  V28     10000 non-null  float64
 28  Amount  10000 non-null  float64
dtypes: float64(29)
memory usage: 2.2 MB

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [ ]:
null = df.isnull().sum().sum()
null

np.int64(0)

In [ ]:
duplicates=df.duplicated().sum()
duplicates

np.int64(0)

In [ ]:
#Scale the data
scaler=StandardScaler()
scaled_df=scaler.fit_transform(df)
X_df=pd.DataFrame(scaled_df,columns=df.columns)
X_df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-0.726092,-0.270865,1.389980,0.762227,-0.236899,0.264052,0.285346,0.131083,-0.384443,0.286120,...,0.370795,0.043066,0.689788,-0.163478,0.083851,0.099198,-0.532722,0.312929,-0.090009,0.459472
1,0.949810,-0.013020,-0.647336,0.110710,0.102482,-0.155239,-0.009963,0.120253,-0.915428,0.051569,...,-0.167706,-0.185510,-0.760673,0.268858,-0.603364,0.188884,0.033761,-0.039088,0.043500,-0.333835
2,-0.725138,-1.235035,0.733929,0.062810,-0.377373,1.293991,0.797185,0.249752,-1.995239,0.392444,...,0.830447,0.336466,1.471338,1.918734,-1.193707,-0.959876,-0.442774,-0.153601,-0.234422,1.696110
3,-0.467623,-0.356408,0.750937,-0.808030,0.042565,0.868121,0.283501,0.353112,-1.885794,0.153501,...,-0.401179,-0.056083,0.258431,-0.326493,-2.015264,1.303733,-0.591732,0.137995,0.217896,0.318445
4,-0.593701,0.452248,0.540940,0.079101,-0.295578,-0.018016,0.613062,-0.163028,0.004829,0.888749,...,0.634808,0.052846,1.513434,-0.218569,0.209441,-0.677493,0.710640,0.524976,0.791442,0.029532

In [ ]:
kmeans = KMeans(n_clusters=3,n_init='auto',random_state=42)
kmeans.fit(X_df)

KMeans(n_clusters=3, random_state=42)

In [ ]:
from scipy.spatial.distance import cdist
distance=cdist(X_df,kmeans.cluster_centers_,'euclidean')
distance.shape

(10000, 3)

In [ ]:
min_distances = np.min(distance,axis=1)
min_distances[:5]

array([2.72323458, 2.48147889, 6.46705846, 4.84083756, 3.04422311])

In [ ]:
thresould = np.percentile(min_distances,99.6)
thresould

np.float64(20.818227126240366)

In [ ]:
filter_anomalies = min_distances > thresould
filter_anomalies.sum()

np.int64(40)

In [ ]:
idx_anomalies = X_df[filter_anomalies].index
idx_anomalies

Index([ 159, 1376, 1619, 2156, 2212, 2439, 2594, 2654, 2756, 2911, 2914, 2917,
       2923, 3443, 5303, 5412, 5413, 5529, 5674, 5704, 5764, 5977, 6489, 6643,
       6672, 7322, 7338, 7470, 7596, 7597, 8124, 8163, 8437, 8442, 8856, 8939,
       8999, 9071, 9304, 9326],
      dtype='int64')

In [ ]:
X_df.iloc[idx_anomalies]

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
159,-3.834960,-9.431468,-5.686284,2.104654,-1.153193,3.584223,4.522820,-0.129306,-1.147362,-1.366035,...,12.960326,2.518824,-3.332963,-7.192555,2.023902,-1.141962,-1.367622,-1.773317,2.499616,20.320071
1376,-2.418627,-3.007869,-2.040269,1.407855,-8.255103,4.877629,10.065097,-1.668099,-0.900585,-0.710429,...,-3.754280,-1.015485,1.764920,5.047600,0.394163,0.499370,1.889565,3.994384,-6.126389,12.890690
1619,-7.150070,-7.528445,-11.441444,4.009433,-27.290908,16.374319,31.878466,-5.938228,-2.347745,-2.195640,...,-19.791952,-5.125945,2.412080,-5.911458,1.395896,1.533320,1.248504,9.496001,15.504724,41.292747
2156,-3.674689,-9.158175,-3.656015,2.370064,-3.748184,0.415459,4.262012,-0.732546,-0.492485,-1.483717,...,12.238043,2.443958,-2.902722,-6.553469,1.000686,-2.487275,-0.031340,-1.778584,2.425582,19.461379
2212,-3.215208,3.026652,-1.687193,-2.215652,-0.775564,1.476574,-4.085387,-11.810305,0.773002,0.285954,...,-5.487786,16.278911,-6.764131,4.300451,-0.071619,-0.100710,-0.275131,1.512629,1.061451,-0.326762
2439,-7.824911,-12.184466,-1.114101,2.453688,9.132442,-5.838093,-6.342982,1.306016,-0.646520,-0.180378,...,7.457408,1.892358,-1.190891,0.083439,-0.193509,-0.965160,0.213631,0.481461,-8.850109,0.299547
2594,-1.524177,-2.246208,-3.438370,1.228373,-9.675750,5.977763,11.396173,-1.403798,-1.962029,-1.585241,...,1.340186,-0.064103,0.668031,4.593911,-1.331986,0.138431,-0.625159,2.898280,-2.338725,15.363209
2654,-4.789278,2.105598,-1.241513,0.500971,0.085842,2.026108,-5.749739,-15.222733,0.203976,0.678419,...,-6.412602,10.683389,-4.582514,5.469079,0.696040,0.498896,-0.683721,3.195176,-2.405010,-0.186922
2756,-6.913533,-7.777855,0.673923,1.964941,6.806898,-3.195860,-8.233600,-4.009462,1.273875,-0.009641,...,-8.166138,-4.784251,2.834458,-1.390803,1.062015,-1.474357,1.074814,8.311982,-4.891511,0.110575
2911,-2.686228,3.031804,-2.148883,-0.012320,-1.157837,1.912165,-10.291944,-18.772044,-2.282244,-4.544346,...,9.779945,-12.357685,6.045469,-0.347143,1.526074,1.239905,-0.878097,-0.345087,2.003279,-0.342960
2914,-3.373200,3.695652,-2.902472,-1.207739,-1.765355,1.981334,-8.937355,-18.411315,-2.194496,-5.294882,...,9.324958,-12.168847,7.149597,4.030761,1.285824,-1.838153,-2.001656,-0.056798,1.939579,-0.342960
2917,-3.739879,4.024385,-3.311076,-1.219267,-2.097347,1.941427,-9.253864,-18.066194,-2.176951,-5.221603,...,9.346601,-12.157911,7.098835,4.164101,1.278457,-1.662420,-1.988491,-0.093582,1.921886,-0.307865
2923,-3.905148,3.607617,-3.148108,-0.862401,-5.619735,4.089370,-8.467954,-17.940479,-3.478436,-4.758658,...,7.665442,-12.315132,7.203751,4.028923,1.400043,-3.318020,-1.465179,-0.536053,0.236821,2.592164
3443,-3.714623,3.817520,-0.826423,0.873673,-0.851728,2.689914,-3.250023,-14.066442,0.064734,3.156273,...,-6.200309,17.285068,-8.783037,4.693132,0.109472,-1.178538,-0.732904,-0.553391,-2.286695,0.529608
5303,-5.568999,-4.538082,1.147149,2.550152,-0.729204,3.260410,5.071755,-3.925819,5.151690,6.359058,...,-9.412953,-2.830911,2.663787,-2.853970,-0.080207,-0.267674,-0.668208,-19.714456,17.574426,2.640649
5412,-5.122199,5.144790,-1.738672,-0.813213,-1.107812,3.567744,-7.050605,-18.638297,1.924263,2.101289,...,-7.743901,24.924799,-13.075731,7.231108,-0.918666,0.443698,0.179878,2.899599,0.714847,-0.318717
5413,-5.493113,5.465089,-2.135876,-0.823017,-1.396947,3.502506,-7.411272,-18.286024,1.944236,2.180633,...,-7.701164,24.941320,-13.130098,7.362344,-0.927329,0.617150,0.191615,2.840865,0.709532,-0.337669
5529,-2.929226,2.764895,-1.911774,0.315165,0.391612,2.228194,-11.964994,-18.467136,-1.730201,-3.957074,...,9.278528,-12.572023,4.706511,-5.042249,0.145020,-1.064163,1.865821,-0.437249,2.038891,-0.226229
5674,-5.338364,-7.092008,-0.360708,-0.605896,3.666111,-2.393637,-2.247011,-0.445511,3.526642,-0.223876,...,-5.838874,-1.062563,1.706055,-2.207487,-0.112139,-0.231802,-1.801655,-4.263348,18.127497,0.696498
5704,-3.460336,3.638453,-2.872887,-0.721282,-1.411653,3.062818,-9.252440,-18.152764,-1.862932,-4.839504,...,9.052531,-12.411618,6.391619,4.045329,-0.281537,-3.019089,0.999503,-0.301489,1.585372,-0.193833
5764,-5.804942,-6.208783,-0.860017,-1.248595,1.079462,-1.033040,0.518983,-0.227636,3.185974,-1.066711,...,-6.308581,-1.311524,2.119518,5.091105,-0.443058,3.979253,-1.677078,-4.768506,16.992790,0.696498
5977,-2.721524,0.817891,-3.019460,1.674092,-0.909811,-1.405361,-3.179512,-0.145699,-0.908862,-4.165654,...,-0.339969,0.695167,0.530152,-0.828498,-0.119606,0.386766,-1.375001,-2.059574,3.158909,-0.029805
6489,-5.859311,5.799066,-2.568552,-0.834925,-1.805068,3.506697,-7.648298,-17.954151,1.958214,2.243065,...,-7.724532,24.940261,-13.175743,7.490511,-0.931320,0.795797,0.206958,2.845997,0.658501,-0.218886
6643,-4.148962,-9.301896,-4.440914,4.578614,-2.416554,1.991460,5.047304,-0.642277,-1.233377,-0.665804,...,13.259267,2.509646,-3.540378,-7.555982,-1.745271,-1.919122,-0.728322,-1.977028,2.528434,21.264070
6672,-14.983013,-19.721707,-3.438525,3.206307,5.931287,-3.227847,1.943436,-2.089185,2.221706,2.825808,...,-22.358221,-5.862051,5.493166,28.391916,-0.995869,12.627877,1.438393,8.277949,13.250672,4.217923
7322,-2.187435,-2.387706,-0.556998,3.140373,0.893392,0.179785,-5.278535,-4.740541,0.114585,0.117952,...,1.712152,-2.862551,-2.108234,-30.856789,0.658977,-6.182844,0.046096,3.876776,1.070313,9.887914
7338,-6.077601,-5.032748,-2.808912,3.936444,-1.606733,1.715267,-2.622200,-7.063458,-0.257333,-0.907899,...,-3.213067,-5.730074,0.136417,-21.329890,0.750248,-5.215750,0.395695,10.289577,-11.408381,9.887914
7470,-4.093759,-10.584956,-3.533452,1.821973,-4.307050,1.750709,3.550237,-0.415419,0.004101,-1.379229,...,13.411215,2.668267,-2.654870,-6.952749,-0.241446,-3.242874,-1.385859,-1.751422,2.578728,21.226492
7596,-6.263641,6.069688,-2.961085,-0.831237,-2.019537,3.395007,-8.084367,-17.598373,1.988352,2.336417,...,-7.716112,24.950480,-13.244909,7.499009,-0.931574,0.938058,0.217721,2.829918,0.571465,-0.290263
7597,-3.811475,3.773463,-2.345726,0.263399,-2.703804,4.071695,-9.648254,-17.705843,-1.737317,-5.057005,...,8.201250,-12.148832,7.426276,3.923763,-0.375363,-3.253722,-1.494049,-0.790992,0.989983,0.558710
8124,-1.228984,4.328928,-10.276740,6.106756,-1.388052,-2.288879,-7.180865,1.670158,-5.758175,-11.480858,...,2.458231,1.877274,-0.190643,-1.295280,-1.996647,3.751683,1.049645,5.217969,4.126763,-0.342960
8163,-0.769976,2.935549,-9.218803,4.466845,-3.995214,-1.687526,-9.295035,2.275916,-3.482913,-10.188317,...,2.318610,2.118733,0.895480,1.298894,-1.328974,-4.253529,0.710186,4.866079,2.644058,-0.342960
8437,-18.006687,-26.543507,1.137865,7.126675,29.103707,-18.177180,-24.559618,-0.568155,5.732049,6.214062,...,-21.615578,-5.060993,-2.326191,-23.763523,3.675056,-5.963931,3.023078,20.367872,-13.106922,-0.050052
8442,-2.388676,5.185054,-10.613509,5.826821,-1.708619,-2.389611,-7.485215,2.421352,-6.075424,-11.801592,...,2.271466,1.999091,-0.050148,-0.976356,-2.038465,2.560095,0.895775,4.629668,3.254765,-0.342960
8856,-1.533817,5.122518,-12.572658,7.042754,-2.465831,-2.443358,-8.563589,2.720573,-5.544982,-10.582695,...,2.449965,2.143036,0.778668,0.649355,-2.033563,-1.801762,0.943362,4.759794,2.935432,-0.342960
8939,-6.981986,-10.447438,-2.137512,0.521710,3.057714,-2.754499,2.068399,-0.633469,1.920068,-1.178166,...,-2.596143,-1.004877,2.313453,21.449517,-0.390474,5.418586,0.002515,4.764564,-5.160179,4.773287
8999,-1.724565,3.759796,-10.301329,4.483432,-4.856065,-1.819069,-10.324574,3.250398,-3.637085,-10.317071,...,1.950251,2.269896,0.805736,1.685669,-1.344232,-4.022478,0.684109,3.508937,2.164780,-0.342960
9071,-3.415347,6.089217,-11.753735,5.817563,-2.594943,-2.539441,-8.518611,3.433876,-6.124311,-11.749983,...,2.142497,2.097233,-0.172739,-0.572474,-2.059375,2.940002,0.901499,3.871968,3.006476,-0.342960
9304,-2.560638,6.026360,-13.712852,7.033557,-3.351874,-2.593369,-9.597176,3.733174,-5.593891,-10.531115,...,2.321882,2.241367,0.656036,1.054103,-2.054537,-1.421703,0.949062,4.001607,2.687452,-0.342960
9326,-2.926806,6.354564,-14.112177,7.021822,-3.655962,-2.649308,-9.942823,4.083320,-5.575080,-10.453776,...,2.358200,2.256304,0.604245,1.193954,-2.063356,-1.245533,0.961583,3.949125,2.681513,-0.342960